# Generated by Django 3.2.14 on 2024-03-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_ingredient_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='recipes',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='restaurants',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='base.Ingredient'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='recipes',
            field=models.ManyToManyField(to='base.Recipe'),
        ),
    ]
